apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-kust
  namespace: flux-system
spec:
  dependsOn:
    - name: gitrepos
  interval: 5m
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: networking-repo
    namespace: flux-system
  path: ./
  prune: true
