apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitrepos
  namespace: flux-system
spec:
  interval: 60m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitrepos
  prune: true
