apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  url: https://github.com/jianxinqi/myinfra.git
