apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  dependsOn: []
  interval: 60m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./networking
  prune: true
